### PR TITLE
Optimal-viewing-position experiment

### PR DESCRIPTION
**Pull request by smathot**
I tested this with the latest revamp (#84). The experiment hangs without crashing upon launching it.

### CODE REVIEW

**Comment by dschreij** [comment]
I'll have a look soon!

**Comment by dschreij** [comment]
I tried to checkout your PR branch directly, but did you use a very old version/commit of osweb by any chance? I could not get the app built. I ended up simply copying the ovp.osexp file to my master branch, and then I could indeed load and start the experiment, but get nothing more than a black screen (and no error messages in the console, alas). So the first challenge has arrived!

**Review by dschreij — CHANGES_REQUESTED** [review]
PR is based on an old commit of osweb? Anyway, the experiment can be extracted and opened, so the important part is ok.

**Comment by smathot** [comment]
I tested this with the latest changes, i.e. the state of #84. However, to keep the PR clean I reset the state to shyras/master and sent only the experiment commit in this PR.

**Comment by smathot** [comment]
The PR still says changes requested. But what kind of changes do you mean?

**Comment by dschreij** [comment]
There are still some discrepancies with osweb/master from shyras and the contents of your PR (or the state of the repo it references to). For example, your repo still contains the `test` folder, which I removed somewhere during the revamp. I thus couldn't easily merge your changes into my master branch, because I got all kinds of weird conflicts.

I didn't feel like solving the batch of git conflicts, so I solved this by just copying the ovp.osexp file in my own repo, since this was the only change (right?).

**Comment by dschreij** [comment]
You can also see the difference in your README.md. It still shows the old build commands. Somehow the branch you sent the PR from was not completely updated, I guess.

**Comment by smathot** [comment]
It's a clean pull request relative to `shyras/master`, just not relative to your branch, probably ;-) But no matter, if you've added it manually you can close this PR. Another trick in these cases that I often use is `git cherry-pick` to select only the commit that I need.

**Pull request closed without merging**
