### PR TITLE
Coroutines

### PR DESCRIPTION
**Pull request by dschreij**
The first working implementation of coroutines for osweb is a fact (as the bundled coroutines.osexp demonstrates), though it still has a lot of rough edges:

- It currently only works when there is no (response) item preceding the coroutines. 
If there is, and the coroutines item contains a keyboard_response item designated by 'abort_on_end', the coroutine directly aborts, or doesn't even seem to start. My guess is that the response to the previous item 'leaks' to the coroutines' keyboard response item, making it fire right away. This problem should be solved by flushing the keyboard buffer somehow before the routines start, but I have yet to find out how.
- The mouse_response item is also implemented as a coroutine, but I have not tested this yet.

All in all, I think we're 80% there with what we currently have. If you can give this a spin and shoot holes in it wherever you can, we should soon reach the 100%

### CODE REVIEW

**Comment by smathot** [comment]
Thanks, I'm going to take a look at this next week!

**Comment by dschreij** [comment]
Great, thanks! I solved the first problem in the meantime (keypress leaking) and will push these commits shortly. I must say it works pretty well now, but I'm sure you will be able to shoot some holes in it when testing it more elaborately.

**Comment by dschreij** [comment]
The coroutines module appears to be fully functional now. I added a (very silly) experiment `coroutines.osexp` to test it, and the behavior of the module in OpenSesame and osweb appears to be the same. Please let me know if you find something!

**Comment by dschreij** [comment]
I expanded the (included) coroutines.osexp experiment to more thoroughly test the coroutines module and all works well, except the calculation of the average accuracy score at the end. This only reflects the last response (so 0% if the last response was incorrect, and 100% when it was correct). I also tested this in OpenSesame, and the same happens there. 
So the question is, am I doing something wrong in my implementation of the experiment, or is this is a bug that just surfaced in both osweb and OpenSesame?

**Comment by smathot** [comment]
I tested the included example experiment, and also the stop-signal task that is bundled with OpenSesame. Both work flawlessly! I haven't inspected the code itself though. I have merged into a new branch `coroutines`. I suggest to keep it separate from the main `1.4` code for now, and then we can decide at a later point (after some more testing) whether we want to include this functionality or not.

**Comment by dschreij** [comment]
Great to hear! The only mistake that I still have to solve is that press or release settings of a keyboard_response item are currently not processed when the item is used inside a coroutine (it only listens to presses now), but that's a minimal change.

**Pull request closed without merging**
